[POWERS]
; All of these options can also be changed via the F5 menu.
Enabled = 1
Invincibility = 1
SuperPunch = 1
BlastPistol = 1
GravityGun = 1
Telekinesis = 1
SuperJump = 1
VehicleBoost = 1
ChaosAura = 0

; 1 = NPCs, 2 = Vehicles, 3 = Both
TargetMode = 3

; 1 = Fun, 2 = Chaos, 3 = Apocalypse
PowerLevel = 2

; 1 = Push, 2 = Pull, 3 = Launch, 4 = Grab
GravityMode = 1

[CONTROLS]
; Virtual-key code decimal
MenuKey = 116
TelekinesisKey = 71
ShockwaveKey = 72
VehicleBoostKey = 66
GravityCycleKey = 74
GravityActionKey = 75
GravityLaunchKey = 76
